
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_webserver
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # Файлы сайта
      - ./website:/var/www/html
      # Конфигурационные файлы Nginx
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Логи выводим наружу
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - web_network
    restart: unless-stopped

  php-fpm:
    image: php:8.3-fpm
    container_name: php_fpm_server
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      # Файлы сайта
      - ./website:/var/www/html
      # Конфигурационные файлы PHP
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./configs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      # Логи выводим наружу
      - ./logs/php-fpm:/var/log/php-fpm
    environment:
      - TZ=Europe/Moscow
    networks:
      - web_network
      - db_network
    restart: unless-stopped





networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

#volumes:
#  mysql_data:
#  redis_data:
